--[[
Steal a Chibi - finish importing voxel FBX models.
Generated by tools/blender/build.py from tools/blender/studio_import.luau. Don't edit the
copy in assets/models; edit the template and rebuild.

The models already ship as Roblox parts in StealAChibi.rbxl. Use this when you want the
FBX meshes instead (a handful of MeshParts per model rather than ~100 parts, which is
lighter on phones):

1. Model tab > Import 3D, pick one of the .fbx files from the fbx folder next to this
   file. Keep "Ignore Vertex Colors" off and keep the meshes separate (don't merge them).
   Repeat for each model; each one lands in Workspace named after its file.
2. Select the imported models in the Explorer.
3. View > Command Bar, paste this whole file and press Enter.

Each selected model is stood upright and turned to face -Z (using its TopMarker and
FrontMarker), scaled to its in-game size, coloured from its piece names, split into limb
groups (characters) and moved into ReplicatedStorage.Assets. The parts version it replaces
goes to ServerStorage.Unsorted, so nothing is lost. Ctrl+Z undoes the whole import.
]]

local META = {
	Char_AdmiralGotetsu = {
		Attributes = {},
		Bounds = { { -1.5938, 0.0, -1.5938 }, { 1.5938, 4.875, 1.4062 } },
		Groups = {
			ArmL = { -1.125, 2.1562, 0.0 },
			ArmR = { 1.125, 2.1562, 0.0 },
			Head = { 0.0, 2.25, 0.0 },
			LegL = { -0.4688, 0.9375, 0.0 },
			LegR = { 0.4688, 0.9375, 0.0 },
			Torso = { 0.0, 0.9375, 0.0 },
		},
		Kind = "Character",
		PreviewTint = "#ADB5BD",
		Size = { 3.1875, 4.875, 3.0 },
	},
	Char_Bolt = {
		Attributes = {},
		Bounds = { { -1.9688, 0.0, -1.5938 }, { 1.9688, 5.4375, 1.7812 } },
		Groups = {
			ArmL = { -1.125, 2.1562, 0.0 },
			ArmR = { 1.125, 2.1562, 0.0 },
			Head = { 0.0, 2.25, 0.0 },
			LegL = { -0.4688, 0.9375, 0.0 },
			LegR = { 0.4688, 0.9375, 0.0 },
			Torso = { 0.0, 0.9375, 0.0 },
		},
		Kind = "Character",
		PreviewTint = "#ADB5BD",
		Size = { 3.9375, 5.4375, 3.375 },
	},
	Char_Daichi = {
		Attributes = {},
		Bounds = { { -2.1562, 0.0, -1.2188 }, { 2.1562, 6.5625, 1.9688 } },
		Groups = {
			ArmL = { -1.5938, 2.4375, 0.0 },
			ArmR = { 1.5938, 2.4375, 0.0 },
			Head = { 0.0, 3.0, 0.0 },
			LegL = { -0.6562, 0.9375, 0.0 },
			LegR = { 0.6562, 0.9375, 0.0 },
			Torso = { 0.0, 0.9375, 0.0 },
		},
		Kind = "Character",
		PreviewTint = "#ADB5BD",
		Size = { 4.3125, 6.5625, 3.1875 },
	},
	Char_Haruto = {
		Attributes = {},
		Bounds = { { -1.5938, 0.0, -1.4062 }, { 1.5938, 4.875, 1.2188 } },
		Groups = {
			ArmL = { -1.125, 2.1562, 0.0 },
			ArmR = { 1.125, 2.1562, 0.0 },
			Head = { 0.0, 2.25, 0.0 },
			LegL = { -0.4688, 0.9375, 0.0 },
			LegR = { 0.4688, 0.9375, 0.0 },
			Torso = { 0.0, 0.9375, 0.0 },
		},
		Kind = "Character",
		PreviewTint = "#ADB5BD",
		Size = { 3.1875, 4.875, 2.625 },
	},
	Char_Hikari = {
		Attributes = {},
		Bounds = { { -1.4062, 0.0, -1.2188 }, { 1.4062, 5.25, 2.3438 } },
		Groups = {
			ArmL = { -1.125, 2.1562, 0.0 },
			ArmR = { 1.125, 2.1562, 0.0 },
			Head = { 0.0, 2.25, 0.0 },
			LegL = { -0.4688, 0.9375, 0.0 },
			LegR = { 0.4688, 0.9375, 0.0 },
			Torso = { 0.0, 0.9375, 0.0 },
		},
		Kind = "Character",
		PreviewTint = "#ADB5BD",
		Size = { 2.8125, 5.25, 3.5625 },
	},
	Char_Hive = {
		Attributes = {},
		Bounds = { { -1.5938, 0.0, -1.2188 }, { 1.5938, 6.0, 1.2188 } },
		Groups = {
			ArmL = { -1.125, 2.1562, 0.0 },
			ArmR = { 1.125, 2.1562, 0.0 },
			Drones = { 0.0, 5.0625, 0.0 },
			Head = { 0.0, 2.25, 0.0 },
			LegL = { -0.4688, 0.9375, 0.0 },
			LegR = { 0.4688, 0.9375, 0.0 },
			Torso = { 0.0, 0.9375, 0.0 },
		},
		Kind = "Character",
		PreviewTint = "#ADB5BD",
		Size = { 3.1875, 6.0, 2.4375 },
	},
	Egg_AdmiralGotetsu = {
		Attributes = {
			Ornament = "Stars",
			ShellHeight = 3.0,
		},
		Bounds = { { -1.4062, 0.0, -1.7812 }, { 1.7812, 3.1875, 1.2188 } },
		Groups = {
			Egg = { 0.0, 1.5, 0.0 },
			Ornament = { 0.0, 1.5, 0.0 },
		},
		Kind = "Egg",
		PreviewTint = "#4361EE",
		Size = { 3.1875, 3.1875, 3.0 },
	},
	Egg_Bolt = {
		Attributes = {
			Ornament = "Crown",
			ShellHeight = 3.0,
		},
		Bounds = { { -1.0312, 0.0, -1.2188 }, { 1.2188, 3.375, 1.0312 } },
		Groups = {
			Egg = { 0.0, 1.5, 0.0 },
			Ornament = { 0.0, 1.5, 0.0 },
		},
		Kind = "Egg",
		PreviewTint = "#ADB5BD",
		Size = { 2.25, 3.375, 2.25 },
	},
	Egg_Daichi = {
		Attributes = {
			Ornament = "Stars",
			ShellHeight = 3.0,
		},
		Bounds = { { -1.5938, 0.0, -1.7812 }, { 1.7812, 3.75, 1.2188 } },
		Groups = {
			Egg = { 0.0, 1.5, 0.0 },
			Ornament = { 0.0, 1.5, 0.0 },
		},
		Kind = "Egg",
		PreviewTint = "#E5383B",
		Size = { 3.375, 3.75, 3.0 },
	},
	Egg_Haruto = {
		Attributes = {
			Ornament = "Crown",
			ShellHeight = 3.0,
		},
		Bounds = { { -1.4062, 0.0, -1.2188 }, { 1.4062, 3.375, 1.2188 } },
		Groups = {
			Egg = { 0.0, 1.5, 0.0 },
			Ornament = { 0.0, 1.5, 0.0 },
		},
		Kind = "Egg",
		PreviewTint = "#F8F9FA",
		Size = { 2.8125, 3.375, 2.4375 },
	},
	Egg_Hikari = {
		Attributes = {
			Ornament = "Horns",
			ShellHeight = 3.0,
		},
		Bounds = { { -1.0312, 0.0, -1.2188 }, { 1.0312, 3.75, 1.4062 } },
		Groups = {
			Egg = { 0.0, 1.5, 0.0 },
			Ornament = { 0.0, 1.5, 0.0 },
		},
		Kind = "Egg",
		PreviewTint = "#F8F9FA",
		Size = { 2.0625, 3.75, 2.625 },
	},
	Egg_Hive = {
		Attributes = {
			Ornament = "Horns",
			ShellHeight = 3.0,
		},
		Bounds = { { -1.7812, 0.0, -1.2188 }, { 1.7812, 3.75, 1.0312 } },
		Groups = {
			Egg = { 0.0, 1.5, 0.0 },
			Ornament = { 0.0, 1.5, 0.0 },
		},
		Kind = "Egg",
		PreviewTint = "#4361EE",
		Size = { 3.5625, 3.75, 2.25 },
	},
}

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ServerStorage = game:GetService("ServerStorage")

local CORNERS = {
	Vector3.new(-1, -1, -1),
	Vector3.new(1, -1, -1),
	Vector3.new(-1, 1, -1),
	Vector3.new(1, 1, -1),
	Vector3.new(-1, -1, 1),
	Vector3.new(1, -1, 1),
	Vector3.new(-1, 1, 1),
	Vector3.new(1, 1, 1),
}

local function folder(parent: Instance, name: string): Instance
	local existing = parent:FindFirstChild(name)
	if existing then
		return existing
	end
	local created = Instance.new("Folder")
	created.Name = name
	created.Parent = parent
	return created
end

local function boundsOf(parts: { BasePart }): (Vector3, Vector3)
	local lo = Vector3.new(math.huge, math.huge, math.huge)
	local hi = Vector3.new(-math.huge, -math.huge, -math.huge)
	for _, part in parts do
		local half = part.Size / 2
		for _, corner in CORNERS do
			local p = part.CFrame * (half * corner)
			lo = Vector3.new(math.min(lo.X, p.X), math.min(lo.Y, p.Y), math.min(lo.Z, p.Z))
			hi = Vector3.new(math.max(hi.X, p.X), math.max(hi.Y, p.Y), math.max(hi.Z, p.Z))
		end
	end
	return lo, hi
end

local function transform(parts: { BasePart }, cframe: CFrame)
	for _, part in parts do
		part.CFrame = cframe * part.CFrame
	end
end

local function settle(part: BasePart)
	part.Anchored = true
	part.CanCollide = false
	part.CanTouch = false
	part.CanQuery = false
	part.CastShadow = false
	part.Massless = true
end

local function shade(color: Color3, factor: number): Color3
	if factor >= 1 then
		return color:Lerp(Color3.new(1, 1, 1), math.min(factor - 1, 1))
	end
	return Color3.new(color.R * factor, color.G * factor, color.B * factor)
end

-- Piece names are "<Group>" or "<Group>__<tags>", tags being any of Orbit, Neon_RRGGBB,
-- Glass_RRGGBB_TT (TT = transparency %) and Tint_FFF (FFF = shell tint factor %).
local function applyTags(part: BasePart, tags: string, meta)
	part.Color = Color3.new(1, 1, 1) -- vertex colours show as authored on white
	part.Material = Enum.Material.SmoothPlastic
	if string.find(tags, "Orbit", 1, true) then
		part:SetAttribute("Orbit", true)
	end
	local neon = string.match(tags, "Neon_(%x%x%x%x%x%x)")
	if neon then
		part.Material = Enum.Material.Neon
		part.Color = Color3.fromHex(neon)
	end
	local glass, alpha = string.match(tags, "Glass_(%x%x%x%x%x%x)_(%d+)")
	if glass then
		part.Material = Enum.Material.Glass
		part.Color = Color3.fromHex(glass)
		part.Transparency = (tonumber(alpha) or 0) / 100
	end
	local tint = string.match(tags, "Tint_(%d+)")
	if tint then
		local factor = (tonumber(tint) or 100) / 100
		part:SetAttribute("Tint", factor)
		part.Color = shade(Color3.fromHex(meta.PreviewTint), factor)
	end
end

local function finish(model: Model): boolean
	local meta = META[model.Name]
	if not meta then
		warn(model.Name .. ": not one of this file's voxel models (name it after its .fbx, e.g. Char_Bolt)")
		return false
	end
	local front: BasePart?, top: BasePart? = nil, nil
	local pieces: { BasePart } = {}
	for _, descendant in model:GetDescendants() do
		if descendant:IsA("BasePart") then
			descendant.Parent = model
			settle(descendant)
			if descendant.Name == "FrontMarker" then
				front = descendant
			elseif descendant.Name == "TopMarker" then
				top = descendant
			else
				table.insert(pieces, descendant)
			end
		end
	end
	for _, child in model:GetChildren() do
		if not child:IsA("BasePart") then
			child:Destroy()
		end
	end
	if not front or not top or #pieces == 0 then
		warn(model.Name .. ": FrontMarker or TopMarker missing; import the .fbx made by tools/blender/build.py")
		return false
	end

	-- 1. stand it up and face -Z, whatever axes the importer used
	local lo, hi = boundsOf(pieces)
	local center = (lo + hi) / 2
	local up = (top.Position - center).Unit
	local toFront = front.Position - center
	local forward = (toFront - up * toFront:Dot(up)).Unit
	local back = -forward
	local current = CFrame.fromMatrix(Vector3.zero, up:Cross(back), up, back)
	transform(pieces, CFrame.new(center) * current:Inverse() * CFrame.new(-center))
	front:Destroy()
	top:Destroy()

	-- 2. scale to its in-game height and put it exactly where the game expects it
	lo, hi = boundsOf(pieces)
	local factor = meta.Size[2] / (hi.Y - lo.Y)
	for _, part in pieces do
		part.Size *= factor
		part.CFrame = CFrame.new(lo + (part.Position - lo) * factor) * part.CFrame.Rotation
	end
	lo = boundsOf(pieces)
	local target = Vector3.new(meta.Bounds[1][1], meta.Bounds[1][2], meta.Bounds[1][3])
	transform(pieces, CFrame.new(target - lo))

	-- 3. per-piece settings; characters get one sub-model per limb, pivoting at its joint
	local isEgg = meta.Kind == "Egg"
	local holders: { [string]: Model } = {}
	for _, part in pieces do
		local group, tags = string.match(part.Name, "^(.-)__(.+)$")
		local groupName: string = group or part.Name
		applyTags(part, tags or "", meta)
		part.Name = groupName
		if groupName == "Ornament" then
			part:SetAttribute("OrnamentPart", true)
		end
		local pivot = meta.Groups[groupName]
		if not isEgg and pivot and part:GetAttribute("Orbit") ~= true then
			local holder = holders[groupName]
			if not holder then
				local created = Instance.new("Model")
				created.Name = groupName
				created.WorldPivot = CFrame.new(pivot[1], pivot[2], pivot[3])
				created.Parent = model
				holders[groupName] = created
				holder = created
			end
			part.Parent = holder
		end
	end
	if isEgg then
		for key, value in meta.Attributes do
			model:SetAttribute(key, value)
		end
		model.WorldPivot = CFrame.new(0, meta.Attributes.ShellHeight / 2, 0)
	else
		local root = Instance.new("Part")
		root.Name = "Root"
		root.Size = Vector3.new(1, 0.1, 1)
		root.CFrame = CFrame.new(0, 0.05, 0)
		root.Transparency = 1
		settle(root)
		root.Parent = model
		model.PrimaryPart = root
	end

	-- 4. replace the parts version (kept in ServerStorage.Unsorted)
	local assets = folder(ReplicatedStorage, "Assets")
	local destination = folder(assets, if isEgg then "Eggs" else "Characters")
	local old = destination:FindFirstChild(model.Name)
	if old and old ~= model then
		old.Name = model.Name .. "_Parts"
		old.Parent = folder(ServerStorage, "Unsorted")
	end
	model.Parent = destination
	return true
end

--[[RUN]]
local ChangeHistoryService = game:GetService("ChangeHistoryService")
local recording = ChangeHistoryService:TryBeginRecording("Finish voxel FBX import")
local done = 0
for _, item in (game:GetService("Selection") :: any):Get() do -- command bar: plugin security
	if item:IsA("Model") and finish(item) then
		done += 1
		print("Imported " .. item:GetFullName())
	end
end
if recording then
	ChangeHistoryService:FinishRecording(recording, Enum.FinishRecordingOperation.Commit)
end
print(string.format("%d voxel model(s) imported", done))
